
package seng2050.lab2;

import java.io.IOException; 
import java.io.PrintWriter;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

public class GenerateValidHTML extends HttpServlet {


  protected void doGet(HttpServletRequest req, HttpServletResponse resp)
            throws IOException {
        
                resp.setContentType("text/html");

        PrintWriter out = resp.getWriter();

        // HTML5 document
        out.println("<!DOCTYPE html>");
        out.println("<html lang=\"en\">");
        out.println("<head>");
        out.println("<meta charset=\"UTF-8\">");
        out.println("<title>Welcome Page</title>");
        out.println("</head>");
        out.println("<body>");

        out.println("<h1>Welcome!</h1>");
        out.println("<p>This page was generated by a Java Servlet.</p>");

        out.println("</body>");
        out.println("</html>");
    }
}



            

        